name = "spinmacho-login-net"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=spinmacho-login.net"
HMAC_KEY = "f0d5f3cec374f38915b6bb112ba82d6c6b6ac90aa3c2a8bb5f88a063ee865e59"
COOKIE_NAME = "7s2"
PLAY_PATH = "visit"
BUTTON_ID = "p8fdfe0e31786c225e04f697b3a4314cb"
GATE_SALT = "929fb8dde74822ed"
GO_URLS = "[\"https://monitorre.top/go/ref\", \"https://firespot.click/go/ref\", \"https://fintechfox.click/go/ref\", \"https://buffout.click/go/ref\"]"
GO_TOKEN = "6c27a2676e6fb97970145a1c9daa1d717ea137c80518a24c"
GO_COOKIE = "213s"
CTA_SELECTOR = ".play-button"
